AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  keiba_fetcher

  SAM Template for keiba_fetcher

Parameters:
  BucketName:
    Type: String
  QueueName:
    Type: String

Resources:
  KeibaFetcherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action: "sqs:*"
              Resource:
                Fn::Sub: "arn:aws:sqs:*:*:${QueueName}"
            - Effect: "Allow"
              Action: "s3:*"
              Resource:
                - Fn::Sub: "arn:aws:s3:::${BucketName}"
                - Fn::Sub: "arn:aws:s3:::${BucketName}/*"
      Timeout: 900
      MemorySize: 192
      Events:
        KeibaFetcher:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
      Environment:
        Variables:
          BUCKET_NAME:
            Ref: BucketName
          QUEUE_NAME:
            Ref: QueueName

  KeibaFetcherFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: "/aws/lambda/${KeibaFetcherFunction}"
      RetentionInDays: 30
