name: build-and-deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - name: Install sam-cli
        run: |
          python -m pip install --upgrade pip
          pip install awscli
          pip install aws-sam-cli
      - name: Install pipenv
        run: pip install pipenv
      - name: Install Dependencies
        run: pipenv sync
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: KeibaFetcher
      - name: build
        run: pipenv run build
      - name: deploy
        if: startsWith(github.ref, 'refs/heads/master')
        run: pipenv run deploy
